import type { UserProfile, Conversation } from "./types"

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: "u1",
    prenom: "Youssef",
    age: 28,
    genre: "homme",
    ville: "Paris",
    paysOrigine: "Maroc",
    photo: "/profil_homme.png",
    traits: ["Travailleur.euse", "Sincère", "Respectueux.se", "Loyal.e", "Patient.e", "Ambitieux.se", "Responsable", "Chaleureux.se"],
    taille: 178,
    styleVestimentaire: "Casual",
    profession: "Ingénieur informatique",
    niveauEtudes: "master",
    niveauPratique: "tres_pratiquant",
    pratiquePriere: "Tous les jours, 5 prières",
    situationMaritale: "jamais_marie",
    avecQui: "Avec ma famille",
    projetMariage: "pret_maintenant",
    souhaitEnfants: "oui",
    attraits: ["La douceur et la piété", "L'ambition et le sérieux", "L'humour bienveillant"],
    repoussants: ["Le mensonge", "L'irrespect", "Le manque de foi"],
    presentation: "Assalamu alaykum, je suis un jeune homme sérieux cherchant à me marier dans les règles islamiques. Je suis pratiquant, travailleur et attaché à mes valeurs.",
    mahram: { nom: "Ahmed Benali", relation: "Père", email: "ahmed.benali@email.com", telephone: "0612345678", statut: "valide" },
    statut: "verifie",
    dateInscription: "2024-11-15",
    likes: ["u4", "u6"],
    matches: ["u4"],
  },
  {
    id: "u2",
    prenom: "Karim",
    age: 32,
    genre: "homme",
    ville: "Lyon",
    paysOrigine: "Algérie",
    photo: "/profil_homme.png",
    traits: ["Calme", "Intelligent.e", "Responsable", "Sage", "Stable", "Fiable", "Spirituel.le", "Patient.e"],
    taille: 182,
    styleVestimentaire: "Qamis/Abaya",
    profession: "Médecin",
    niveauEtudes: "doctorat",
    niveauPratique: "tres_pratiquant",
    pratiquePriere: "Tous les jours, 5 prières",
    situationMaritale: "divorce",
    avecQui: "Seul.e",
    projetMariage: "pret_maintenant",
    souhaitEnfants: "oui",
    attraits: ["La piété et la modestie", "Le calme et la sagesse", "La loyauté familiale"],
    repoussants: ["La superficialité", "Le manque de respect", "L'instabilité"],
    presentation: "Médecin à Lyon, divorcé sans enfants. Je cherche une femme pieuse, calme et sérieuse pour construire un foyer islamique solide. Je suis quelqu'un de stable et attentionné.",
    mahram: { nom: "Omar Hadj", relation: "Frère", email: "omar.hadj@email.com", telephone: "0687654321", statut: "valide" },
    statut: "verifie",
    dateInscription: "2024-10-03",
    likes: ["u5"],
    matches: [],
  },
  {
    id: "u3",
    prenom: "Ibrahim",
    age: 25,
    genre: "homme",
    ville: "Marseille",
    paysOrigine: "Sénégal",
    photo: "/profil_homme.png",
    traits: ["Joyeux.se", "Dynamique", "Sociable", "Drôle", "Optimiste", "Spontané.e"],
    taille: 175,
    styleVestimentaire: "Casual",
    profession: "Commercial",
    niveauEtudes: "licence",
    niveauPratique: "pratiquant",
    pratiquePriere: "Je prie parfois",
    situationMaritale: "jamais_marie",
    avecQui: "En colocation",
    projetMariage: "1_3_ans",
    souhaitEnfants: "oui",
    attraits: ["La joie de vivre", "La bienveillance", "Le partage"],
    repoussants: ["La tristesse permanente", "La jalousie", "Le manque d'ouverture"],
    presentation: "Salam ! Jeune homme joyeux et sérieux dans mes démarches. Je cherche une partenaire de vie avec qui partager bonheur et foi.",
    mahram: { nom: "Moussa Diallo", relation: "Oncle", email: "moussa.diallo@email.com", telephone: "0698765432", statut: "en_attente" },
    statut: "actif",
    dateInscription: "2024-12-01",
    likes: ["u6"],
    matches: [],
  },
  {
    id: "u4",
    prenom: "Fatima",
    age: 26,
    genre: "femme",
    ville: "Paris",
    paysOrigine: "Maroc",
    photo: "/profil_femme.png",
    traits: ["Attentionné.e", "Sincère", "Doux.ce", "Affectueux.se", "Sage", "Cultivé.e", "Romantique", "Fidèle"],
    taille: 165,
    styleVestimentaire: "Qamis/Abaya",
    profession: "Enseignante",
    niveauEtudes: "master",
    niveauPratique: "tres_pratiquant",
    pratiquePriere: "Tous les jours, 5 prières",
    situationMaritale: "jamais_marie",
    avecQui: "Avec ma famille",
    projetMariage: "pret_maintenant",
    souhaitEnfants: "oui",
    attraits: ["La piété sincère", "La stabilité et la sécurité", "L'intelligence et la douceur"],
    repoussants: ["L'arrogance", "La négligence religieuse", "Le manque d'ambition"],
    presentation: "Enseignante parisienne, très pratiquante. Je cherche un homme pieux, doux et sérieux pour un mariage dans le respect de l'islam. Famille très importante pour moi.",
    mahram: { nom: "Hassan Benali", relation: "Père", email: "hassan.benali@email.com", telephone: "0612340000", statut: "valide" },
    statut: "verifie",
    dateInscription: "2024-11-20",
    likes: ["u1", "u2"],
    matches: ["u1"],
  },
  {
    id: "u5",
    prenom: "Meryem",
    age: 29,
    genre: "femme",
    ville: "Lyon",
    paysOrigine: "Tunisie",
    photo: "/profil_femme.png",
    traits: ["Indépendant.e", "Ambitieux.se", "Intelligent.e", "Moderne", "Déterminé.e", "Responsable", "Charismatique"],
    taille: 162,
    styleVestimentaire: "Chic",
    profession: "Avocate",
    niveauEtudes: "master",
    niveauPratique: "pratiquant",
    pratiquePriere: "Je prie parfois",
    situationMaritale: "jamais_marie",
    avecQui: "Seul.e",
    projetMariage: "1_3_ans",
    souhaitEnfants: "oui",
    attraits: ["L'intelligence et l'ambition", "La maturité émotionnelle", "La communication ouverte"],
    repoussants: ["Le machisme", "L'immaturité", "Le manque de respect"],
    presentation: "Avocate lyonnaise, pratiquante et indépendante. Je cherche un homme mature, respectueux et ambitieux pour construire un avenir ensemble dans l'islam.",
    mahram: { nom: "Tarek Mansour", relation: "Frère", email: "tarek.mansour@email.com", telephone: "0677889900", statut: "valide" },
    statut: "verifie",
    dateInscription: "2024-09-15",
    likes: ["u2"],
    matches: [],
  },
  {
    id: "u6",
    prenom: "Khadija",
    age: 24,
    genre: "femme",
    ville: "Marseille",
    paysOrigine: "Algérie",
    photo: "/profil_femme.png",
    traits: ["Créatif.ve", "Joyeux.se", "Spontané.e", "Affectueux.se", "Sociable", "Chaleureux.se"],
    taille: 158,
    styleVestimentaire: "Casual",
    profession: "Designer graphique",
    niveauEtudes: "licence",
    niveauPratique: "guid_allah",
    pratiquePriere: "J'aimerais m'y mettre",
    situationMaritale: "jamais_marie",
    avecQui: "Avec ma famille",
    projetMariage: "1_3_ans",
    souhaitEnfants: "sais_pas",
    attraits: ["La créativité partagée", "La joie au quotidien", "La bienveillance"],
    repoussants: ["La rigidité excessive", "Le manque d'humour", "L'égoïsme"],
    presentation: "Designer créative et joyeuse, en chemin vers une pratique plus solide. Je cherche quelqu'un de bienveillant pour cheminer ensemble vers Allah.",
    mahram: { nom: "Riad Bensalem", relation: "Père", email: "riad.bensalem@email.com", telephone: "0654321098", statut: "en_attente" },
    statut: "actif",
    dateInscription: "2024-12-10",
    likes: ["u1", "u3"],
    matches: [],
  },
  {
    id: "u7",
    prenom: "Bilal",
    age: 35,
    genre: "homme",
    ville: "Toulouse",
    paysOrigine: "Turquie",
    photo: "/profil_homme.png",
    traits: ["Stable", "Fiable", "Patient.e", "Tolérant.e", "Chaleureux.se", "Responsable"],
    taille: 180,
    styleVestimentaire: "Affaires",
    profession: "Entrepreneur",
    niveauEtudes: "licence",
    niveauPratique: "pratiquant",
    pratiquePriere: "Tous les jours, 5 prières",
    situationMaritale: "veuf",
    avecQui: "Avec mes enfants",
    projetMariage: "pret_maintenant",
    souhaitEnfants: "oui",
    attraits: ["La maturité et la sagesse", "L'amour des enfants", "La stabilité familiale"],
    repoussants: ["L'instabilité", "Le manque de patience", "La superficialité"],
    presentation: "Entrepreneur à Toulouse, veuf avec un enfant. Je cherche une femme mature, aimante et pieuse pour recomposer un foyer chaleureux dans le respect de notre deen.",
    mahram: { nom: "Mustafa Yilmaz", relation: "Frère", email: "mustafa.yilmaz@email.com", telephone: "0666778899", statut: "valide" },
    statut: "verifie",
    dateInscription: "2024-08-22",
    likes: [],
    matches: [],
  },
  {
    id: "u8",
    prenom: "Amina",
    age: 31,
    genre: "femme",
    ville: "Bordeaux",
    paysOrigine: "Mauritanie",
    photo: "/profil_femme.png",
    traits: ["Spirituel.le", "Sage", "Paisible", "Ordonné.e", "Cultivé.e", "Perfectionniste", "Sensible"],
    taille: 168,
    styleVestimentaire: "Qamis/Abaya",
    profession: "Médecin",
    niveauEtudes: "doctorat",
    niveauPratique: "tres_pratiquant",
    pratiquePriere: "Tous les jours, 5 prières",
    situationMaritale: "jamais_marie",
    avecQui: "Seul.e",
    projetMariage: "pret_maintenant",
    souhaitEnfants: "oui",
    attraits: ["La spiritualité profonde", "La douceur et la sérénité", "L'engagement religieux sincère"],
    repoussants: ["Le mensonge", "L'arrogance", "La médiocrité spirituelle"],
    presentation: "Médecin et pratiquante sérieuse, je cherche un homme pieux et équilibré pour un zawaj béni. L'islam est au centre de ma vie et j'espère le partager avec mon époux.",
    mahram: { nom: "Cheikh Mbaye", relation: "Père", email: "cheikh.mbaye@email.com", telephone: "0611223344", statut: "valide" },
    statut: "verifie",
    dateInscription: "2024-07-08",
    likes: [],
    matches: [],
  },
]

export const CURRENT_USER: UserProfile = {
  id: "me",
  prenom: "Utilisateur",
  age: 27,
  genre: "homme",
  ville: "Paris",
  paysOrigine: "France",
    photo: "/profil_homme.png",
  traits: ["Sincère", "Travailleur.euse", "Responsable", "Loyal.e"],
  taille: 176,
  styleVestimentaire: "Casual",
  profession: "Développeur",
  niveauEtudes: "master",
  niveauPratique: "pratiquant",
  pratiquePriere: "Je prie parfois",
  situationMaritale: "jamais_marie",
  avecQui: "En colocation",
  projetMariage: "pret_maintenant",
  souhaitEnfants: "oui",
  attraits: ["La piété", "La douceur", "L'intelligence"],
  repoussants: ["Le mensonge", "L'arrogance", "L'irrespect"],
  presentation: "Jeune homme sérieux en quête d'une épouse pieuse et douce.",
  mahram: { nom: "Salim Malik", relation: "Frère", email: "salim.malik@email.com", telephone: "0601020304", statut: "valide" },
  statut: "verifie",
  dateInscription: "2025-01-01",
  likes: [],
  matches: [],
}

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv1",
    user1Id: "me",
    user2Id: "u4",
    mahramId: "mahram_u4",
    mahramApprouve: true,
    messages: [
      { id: "m1", senderId: "u4", senderName: "Fatima", content: "Assalamu alaykum, je suis heureuse que notre match ait été approuvé.", timestamp: "2025-01-10T10:00:00" },
      { id: "m2", senderId: "me", senderName: "Utilisateur", content: "Wa alaykum assalam, moi également. Votre profil m'inspire vraiment confiance.", timestamp: "2025-01-10T10:05:00" },
      { id: "m3", senderId: "mahram", senderName: "Hassan Benali (Mahram)", content: "Assalamu alaykum, je suis le père de Fatima. Je supervise cet échange. Barak Allahu fikoum.", timestamp: "2025-01-10T10:10:00" },
      { id: "m4", senderId: "u4", senderName: "Fatima", content: "Pouvez-vous me parler de votre projet de mariage et de vos valeurs familiales ?", timestamp: "2025-01-10T10:15:00" },
    ],
  },
]

export const ADMIN_STATS = {
  totalUtilisateurs: 1247,
  totalMatchs: 328,
  mahramEnAttente: 47,
  messagesSignales: 12,
  photosEnAttente: 23,
  nouveauxCeJour: 18,
}

export const NIVEAUX_PRATIQUE_LABELS: Record<string, string> = {
  tres_pratiquant: "Très pratiquant(e)",
  pratiquant: "Pratiquant(e)",
  occasions: "Pour les occasions",
  guid_allah: "Inch'Allah qu'Il me guide",
}

export const NIVEAUX_ETUDES_LABELS: Record<string, string> = {
  sans_diplome: "Sans diplôme",
  bac: "Baccalauréat",
  bep: "BEP",
  cap: "CAP",
  bts: "BTS",
  licence: "Licence",
  master: "Master",
  doctorat: "Doctorat",
  autre: "Autre",
}

export const PROJET_MARIAGE_LABELS: Record<string, string> = {
  pret_maintenant: "Prêt(e) maintenant",
  "1_3_ans": "Entre 1 et 3 ans",
  "plus_3_ans": "Plus de 3 ans",
  pas_pret: "Pas encore prêt(e)",
}

export const SITUATION_MARITALE_LABELS: Record<string, string> = {
  jamais_marie: "Jamais marié(e)",
  divorce: "Divorcé(e)",
  separe: "Séparé(e)",
  veuf: "Veuf / Veuve",
}

export const SILHOUETTES_LABELS: Record<string, string> = {
  mince: "Mince",
  musclé: "Musclé(e)",
  normale: "Normale",
  ronde: "Ronde",
}

export const STYLES_AMOUR_LABELS: Record<string, string> = {
  romantique: "Romantique",
  attentionne: "Attentionné(e)",
  independant: "Indépendant(e)",
  fusionnel: "Fusionnel(le)",
  doux: "Doux(ce)",
  passionne: "Passionné(e)",
  protecteur: "Protecteur(rice)",
  solitaire: "Solitaire",
  confiance: "Besoin de temps pour faire confiance",
}

export const STYLES_VIE_LABELS: Record<string, string> = {
  casanier: "Plutôt casanier(ère)",
  sorties: "Plutôt sorties",
  sportif: "Sportif(ve)",
  fetard: "Fêtard(e)",
  travailleur: "Travailleur(se)",
  voyageur: "Voyageur(se)",
  famille_importante: "Famille importante",
  amis_importants: "Ami(es) important(es)",
  vie_simple: "Vie simple",
  toujours_mouvement: "Toujours en mouvement",
  aime_imprévus: "J'aime les imprévus",
  aime_organiser: "J'aime organiser à l'avance",
}

export const GESTIONS_CONFLITS_LABELS: Record<string, string> = {
  discuter_calmement: "Je préfère discuter calmement",
  besoin_temps: "J'ai besoin de temps pour me calmer",
  m_isoler: "Je préfère m'isoler avant de reparler",
  fermer_moment: "Je peux me fermer sur le moment",
  mal_exprimer: "J'ai du mal à exprimer ce que je ressens",
  rancunier: "Je peux être rancunier(ère)",
  hausser_ton: "Je peux hausser le ton",
  prendre_coeur: "Je prends parfois les choses trop à cœur",
  eviter_conflit: "Je préfère éviter le conflit",
  garder_pour_moi: "Je garde parfois les choses pour moi",
  mal_reconnaître_torts: "J'ai du mal à reconnaître mes torts",
  besoin_qu_on_vienne: "J'ai besoin qu'on vienne vers moi",
  revenir_discuter: "Je reviens discuter une fois calmé(e)",
  chercher_compromis: "Je cherche un compromis",
  m_excuser: "Je peux m'excuser quand je comprends que j'ai blessé",
  preserver_respect: "Je veux préserver le respect même en conflit",
}

export const ORIGINES_PARENTS_LABELS: Record<string, string> = {
  algerie: "Algérie",
  maroc: "Maroc",
  tunisie: "Tunisie",
  senegal: "Sénégal",
  mali: "Mali",
  turquie: "Turquie",
  liban: "Liban",
  pakistan: "Pakistan",
  bangladesh: "Bangladesh",
  indonesie: "Indonésie",
  bosnie: "Bosnie",
  kosovo: "Kosovo",
  france: "France",
  autre: "Autre",
}

export const ALL_TRAITS = [
  "Travailleur.euse", "Créatif.ve", "Calme", "Attentionné.e", "Charismatique",
  "Élégant.e", "Charmeur.se", "Souple", "Aventurier.ère", "Joyeux.se",
  "Énergique", "Amical.e", "Idéaliste", "Indépendant.e", "Intelligent.e",
  "Intuitif.ve", "Affectueux.se", "Logique", "Aimable", "Loyal.e",
  "Fidèle", "Soigné.e", "Optimiste", "Ordonné.e", "Passionné.e",
  "Patient.e", "Paisible", "Perfectionniste", "Persuasif.ve", "Ponctuel.le",
  "Fiable", "Ingénieux.se", "Respectueux.se", "Responsable", "Romantique",
  "Sensible", "Sentimental.e", "Simple", "Spontané.e", "Moderne",
  "Drôle", "Doux.ce", "Sincère", "Sociable", "Spirituel.le",
  "Stable", "Tolérant.e", "Chaleureux.se", "Sage", "Courageux.se",
  "Confiant.e", "Déterminé.e", "Cultivé.e", "Dynamique", "Facile à vivre", "Ambitieux.se"
]

export const PAYS = [
  "Algérie", "Maroc", "Tunisie", "Mauritanie", "Mali", "Sénégal", "Côte d'Ivoire",
  "Guinée", "Cameroun", "Niger", "Tchad", "Libye", "Égypte", "Jordanie",
  "Arabie Saoudite", "Émirats Arabes Unis", "Qatar", "Koweït", "Pakistan",
  "Bangladesh", "Indonésie", "Turquie", "France", "Belgique", "Suisse", "Autre"
]

export const VILLES_FRANCE = [
  // Ile-de-France
  "Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil",
  "Nanterre", "Vitry-sur-Seine", "Créteil", "Asnières-sur-Seine", "Versailles",
  "Colombes", "Aulnay-sous-Bois", "Rueil-Malmaison", "Aubervilliers", "Champigny-sur-Marne",
  "Saint-Maur-des-Fossés", "Drancy", "Issy-les-Moulineaux", "Levallois-Perret", "Noisy-le-Grand",
  "Antony", "Neuilly-sur-Seine", "Clichy", "Ivry-sur-Seine", "Clamart", "Sartrouville",
  "Épinay-sur-Seine", "Maisons-Alfort", "Meaux", "Chelles", "Pantin", "Évry-Courcouronnes",
  "Fontenay-sous-Bois", "Bondy", "Le Blanc-Mesnil", "Bobigny", "Vincennes", "Sarcelles",
  "Sevran", "Cergy", "Pontoise", "Saint-Ouen-sur-Seine", "Mantes-la-Jolie", "Poissy",
  // Auvergne-Rhone-Alpes
  "Lyon", "Grenoble", "Saint-Étienne", "Villeurbanne", "Clermont-Ferrand",
  "Vénissieux", "Valence", "Chambéry", "Annecy", "Vaulx-en-Velin", "Caluire-et-Cuire",
  "Bron", "Villefranche-sur-Saône", "Saint-Priest", "Roanne", "Bourg-en-Bresse",
  "Montélimar", "Annemasse", "Thonon-les-Bains", "Romans-sur-Isère", "Aurillac",
  "Le Puy-en-Velay", "Oyonnax", "Albertville", "Bourgoin-Jallieu", "Moulins",
  // Provence-Alpes-Cote d'Azur
  "Marseille", "Nice", "Toulon", "Aix-en-Provence", "Avignon", "Antibes",
  "Cannes", "La Seyne-sur-Mer", "Hyères", "Fréjus", "Arles", "Grasse",
  "Martigues", "Aubagne", "Gap", "Istres", "Salon-de-Provence", "Vitrolles",
  "Cagnes-sur-Mer", "Six-Fours-les-Plages", "Menton", "Draguignan", "Digne-les-Bains",
  // Occitanie
  "Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers", "Narbonne",
  "Carcassonne", "Sète", "Albi", "Tarbes", "Castres", "Rodez", "Agde",
  "Montauban", "Lunel", "Millau", "Auch", "Cahors", "Foix", "Mende",
  "Pamiers", "Alès", "Frontignan", "Bagnols-sur-Cèze",
  // Nouvelle-Aquitaine
  "Bordeaux", "Limoges", "Poitiers", "Pau", "Mérignac", "La Rochelle",
  "Pessac", "Talence", "Angoulême", "Brive-la-Gaillarde", "Niort", "Bayonne",
  "Agen", "Périgueux", "Mont-de-Marsan", "Biarritz", "Villeneuve-sur-Lot",
  "Châtellerault", "Bergerac", "Rochefort", "Saintes", "Dax", "Cognac",
  "Tulle", "Guéret",
  // Pays de la Loire
  "Nantes", "Angers", "Le Mans", "Saint-Nazaire", "Cholet", "La Roche-sur-Yon",
  "Laval", "Saint-Herblain", "Rezé", "Saumur", "Les Sables-d'Olonne",
  "Fontenay-le-Comte", "Mayenne", "Château-Gontier", "Segré",
  // Bretagne
  "Rennes", "Brest", "Quimper", "Lorient", "Vannes", "Saint-Malo", "Saint-Brieuc",
  "Lanester", "Fougères", "Concarneau", "Lannion", "Morlaix", "Vitré",
  "Dinan", "Pontivy", "Loudéac", "Guingamp", "Ploemeur",
  // Normandie
  "Rouen", "Le Havre", "Caen", "Cherbourg-en-Cotentin", "Évreux", "Dieppe",
  "Saint-Lô", "Alençon", "Lisieux", "Argentan", "Fécamp", "Bayeux",
  "Granville", "Avranches", "Coutances", "Vire", "Flers",
  // Grand Est
  "Strasbourg", "Reims", "Metz", "Mulhouse", "Nancy", "Colmar", "Troyes",
  "Charleville-Mézières", "Châlons-en-Champagne", "Épinal", "Thionville",
  "Haguenau", "Illkirch-Graffenstaden", "Schiltigheim", "Saint-Dizier",
  "Sélestat", "Bar-le-Duc", "Verdun", "Forbach", "Sarreguemines", "Saverne",
  // Hauts-de-France
  "Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkerque", "Calais",
  "Villeneuve-d'Ascq", "Valenciennes", "Boulogne-sur-Mer", "Douai", "Arras",
  "Wattrelos", "Marcq-en-Barœul", "Cambrai", "Lens", "Liévin", "Maubeuge",
  "Laon", "Beauvais", "Saint-Quentin", "Compiègne", "Creil", "Soissons",
  // Bourgogne-Franche-Comte
  "Dijon", "Besançon", "Belfort", "Chalon-sur-Saône", "Auxerre", "Nevers",
  "Mâcon", "Sens", "Le Creusot", "Beaune", "Montbéliard", "Dole",
  "Lons-le-Saunier", "Vesoul", "Pontarlier", "Autun", "Gray",
  // Centre-Val de Loire
  "Tours", "Orléans", "Bourges", "Blois", "Châteauroux", "Chartres",
  "Joué-lès-Tours", "Dreux", "Vierzon", "Montargis", "Vendôme", "Issoudun",
  "Amboise", "Chinon", "Loches",
  // Corse
  "Ajaccio", "Bastia", "Porto-Vecchio", "Corte", "Calvi", "Propriano",
  // DOM-TOM
  "Fort-de-France", "Saint-Denis (Réunion)", "Pointe-à-Pitre", "Cayenne",
  "Mamoudzou", "Nouméa", "Papeete"
]
